---
title: "driver_modelling"
author: "Annie George"
date: "November 6, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(readxl)
library(xlsx)
library(sqldf)
library(dplyr)
library(tidyr)
library(caret)
library(janitor)
library(MASS)
library(fpp2)
library(cluster)
```
```{r}
sun=read_excel("clean_data.xlsx",  col_names=TRUE)
sun$average_customer_reviews_int = as.factor(round(sun$average_customer_review))
sun$title=as.factor(sun$title)
sun$asin=as.factor(sun$asin)
sun$upc_code=as.factor(sun$upc_code)
sun$product_group=as.factor(sun$product_group)
sun$category=as.factor(sun$category)
sun$subcategory=as.factor(sun$subcategory)
sun$replenishment_category=as.factor(sun$replenishment_category)
sun$platform1 = as.factor(sun$platform1)
sun$platform2 = as.factor(sun$platform2)
sun$platform_type = as.factor(sun$platform_type)
sun=sun[,!names(sun) %in% c("ordered_amount_trend", 
                            "ordered_amount_year_over_year_trend", 
                            "orders_trend", "orders_year_over_year_trend", 
                            "ordered_units_trend", 
                            "ordered_units_year_over_year_trend", 
                            "shipped_amount_trend", 
                            "shipped_amount_year_over_year_trend", 
                            "shipped_units_trend", 
                            "shipped_units_year_over_year_trend",  
                            "unfilled_customer_ordered_units_trend", 
                            "unfilled_customer_ordered_units_year_over_year_trend", 
                            "unique_visitors_trend", 
                            "unique_visitors_year_over_year_trend", 
                            "conversion_rate_trend", 
                            "conversion_rate_year_over_year_trend", 
                            "shipped_cost_of_goods_sold_trend", 
                            "shipped_cost_of_goods_sold_year_over_year_trend", 
                            "page_views_year_over_year_trend",  
                            "page_views_trend",
                            "conversion_percentile", 
                            "x1_week_forecast", 
                            "x4_week_forecast", 
                            "x12_week_forecast", 
                            "shipped_cost_of_goods_sold", 
                            "currency_code")]
                         #   "sellable_on_hand_cost", 
                        #    "unsellable_on_hand_cost", 
                        #   )] 
sun$week_number=as.factor(sun$week_number)
sun$national_holiday=as.factor(sun$national_holiday)
sun=sun[,-c(1:2, 3, 4,  7, 9, 20, 21)]
```

Get all the numerical variables in the dataset
```{r}
num_var = which(sapply(sun, is.numeric)) #index vector numeric variables
num_var= names(num_var) #saving names vector for use later on
num_var
```

Part I: mixed data type clustering: gower distance method

```{r}

features=sun #[,-c(1:2, 6, 17)] #remove ordderd units
gower_dist <- daisy(sun[,!names(sun) %in% "shipped_units"], #[,-c(1:2, 6, 17)],
                    metric = "gower",
                    type = list(logratio = 3))
gower_mat <- as.matrix(gower_dist)

#similar product
sun[which(gower_mat == min(gower_mat[gower_mat != min(gower_mat)]),
        arr.ind = TRUE)[1, ], ]


#dissimialr product
sun[which(gower_mat == max(gower_mat[gower_mat != max(gower_mat)]),
        arr.ind = TRUE)[1, ], ]


# Calculate silhouette width for many k using PAM

sil_width <- c(NA)
for(i in 2:10){
  
  pam_fit <- pam(gower_dist,
                 diss = TRUE,
                 k = i)
  
  sil_width[i] <- pam_fit$silinfo$avg.width
  
}

# Plot sihouette width (higher is better)

plot(1:10, sil_width,
     xlab = "Number of clusters",
     ylab = "Silhouette Width")
lines(1:10, sil_width)

pam_fit <- pam(gower_dist, diss = TRUE, k = 2)

library(dplyr)
pam_results <- sun %>%
  dplyr::select(-title) %>%
  mutate(cluster = pam_fit$clustering) %>%
  group_by(cluster) %>%
  do(the_summary = summary(.))

pam_results$the_summary

sun[pam_fit$medoids, ]
clusplot(pam_fit, color = TRUE)
table(pam_fit$clustering, sun$title)

table(pam_fit$clustering, sun$category)


table(pam_fit$clustering, sun$asin)

table(pam_fit$clustering, sun$platform_type)


table(pam_fit$clustering, sun$customer_reviews)

table(pam_fit$clustering, sun$average_customer_reviews_int)

table(pam_fit$clustering, sun$subcategory)

table(pam_fit$clustering, sun$week_start
      )

table(pam_fit$clustering, sun$product_group)

table(pam_fit$clustering, sun$list_price)

table(pam_fit$clustering, sun$list_price)

```

```{r}
library(Rtsne)
tsne_obj <- Rtsne(gower_dist, is_distance = TRUE)
tsne_data <- tsne_obj$Y %>%
  data.frame() %>%
  setNames(c("X", "Y")) %>%
  mutate(cluster = factor(pam_fit$clustering),
         name = sun$title)

ggplot(aes(x = X, y = Y), data = tsne_data) +
  geom_point(aes(color = cluster))

#row_1=rownames(tsne_data$cluster==1)
#cluster1

tsne_cat <- tsne_obj$Y %>%
  data.frame() %>%
  setNames(c("X", "Y")) %>%
  mutate(cluster = factor(pam_fit$clustering),
         name = sun$category)

ggplot(aes(x = X, y = Y), data = tsne_cat) +
  geom_point(aes(color = cluster))


tsne_platform <- tsne_obj$Y %>%
  data.frame() %>%
  setNames(c("X", "Y")) %>%
  mutate(cluster = factor(pam_fit$clustering),
         name = sun$platform_type)

ggplot(aes(x = X, y = Y), data = tsne_data) +
  geom_point(aes(color = cluster))

unique(tsne_data$name[tsne_data$cluster==1])
unique(tsne_data$name[tsne_data$cluster==2])

```

```{r}
#library(dplyr)
library(reshape2)

cluster1=sun[pam_fit$clustering==1,]
c1_uniq=as.data.frame(as.character(unique(cluster1$title)))
names(c1_uniq) = "cluster1"
c1_uniq_week=as.character(sort(unique(cluster1$week_number)))

ggplot(data= melt(cluster1), aes(x=variable, y=value)) +
    stat_boxplot(geom ='errorbar') +
    geom_boxplot(aes(fill=variable)) +
    coord_cartesian(ylim = c(0,250)) +
    theme(axis.text.x = element_text(angle = 90, hjust = 1), legend.position="none") 

cluster2=sunCluster[kmeansPCA$clust==sunclust[2],]
c2_uniq=as.data.frame(as.character(unique(cluster2$title)))
names(c2_uniq) = "cluster2"
c2_uniq_week=as.character(sort(unique(cluster2$week_number)))

ggplot(data= melt(cluster2), aes(x=variable, y=value)) +
    stat_boxplot(geom ='errorbar') +
    geom_boxplot(aes(fill=variable)) +
    coord_cartesian(ylim = c(0, 7.5)) +
    theme(axis.text.x = element_text(angle = 90, hjust = 1), legend.position="none") 

cluster3=sunCluster[kmeansPCA$clust==sunclust[3],]
c3_uniq=as.data.frame(as.character(unique(cluster3$title)))
names(c3_uniq) = "cluster3"
c3_uniq_week=as.character(sort(unique(cluster3$week_number)))

ggplot(data= melt(cluster3), aes(x=variable, y=value)) +
    stat_boxplot(geom ='errorbar') +
    geom_boxplot(aes(fill=variable)) +
    coord_cartesian(ylim = c(0, 8)) +
    theme(axis.text.x = element_text(angle = 90, hjust = 1), legend.position="none") 

cluster4=sunCluster[kmeansPCA$clust==sunclust[4],]
c4_uniq=as.data.frame(as.character(unique(cluster4$title)))
names(c4_uniq) = "cluster4"
c4_uniq_week=as.character(sort(unique(cluster4$week_number)))

ggplot(data= melt(cluster4), aes(x=variable, y=value)) +
    stat_boxplot(geom ='errorbar') +
    geom_boxplot(aes(fill=variable)) +
    coord_cartesian(ylim = c(0, 25)) +
    theme(axis.text.x = element_text(angle = 90, hjust = 1), legend.position="none") 

cluster5=sunCluster[kmeansPCA$clust==sunclust[5],]
c5_uniq=as.data.frame(as.character(unique(cluster5$title)))
names(c5_uniq) = "cluster5"
c5_uniq_week=as.character(sort(unique(cluster5$week_number)))

ggplot(data= melt(cluster5), aes(x=variable, y=value)) +
    stat_boxplot(geom ='errorbar') +
    geom_boxplot(aes(fill=variable)) +
    coord_cartesian(ylim = c(0, 25)) +
    theme(axis.text.x = element_text(angle = 90, hjust = 1), legend.position="none") 

cluster6=sunCluster[kmeansPCA$clust==sunclust[6],]
c6_uniq=as.data.frame(as.character(unique(cluster6$title)))
names(c6_uniq) = "cluster6"
c6_uniq_week=as.character(sort(unique(cluster6$week_number)))

ggplot(data= melt(cluster6), aes(x=variable, y=value)) +
    stat_boxplot(geom ='errorbar') +
    geom_boxplot(aes(fill=variable)) +
    coord_cartesian(ylim = c(0, 12)) +
    theme(axis.text.x = element_text(angle = 90, hjust = 1), legend.position="none") 

library(qpcR)
product_clusters=qpcR:::cbind.na(c1_uniq, c2_uniq, c3_uniq, c4_uniq, c5_uniq, c6_uniq) #, c3_uniq, c4_uniq, c5_uniq, c6_uniq)
product_clusters

#p <- plot_ly(carsDf,x=Comp.1,y=Comp.2,text=rownames(carsDf),
#             mode="markers",color = cluster_name,marker=list(size=11))
#p <- layout(p,title="PCA Clusters from Hierachical Clustering of Cars Data",
#            xaxis=list(title="PC1"),
#            yaxis=list(title="PC2"))
```

```{r}
c1=unique(cluster1$title)
c2=unique(cluster2$title)
c1_not_in_c2 = unique(cluster1$title[!cluster1$title %in% c2])
c2_not_in_c1 = unique(cluster2$title[!cluster2$title %in% c1])
common = unique(cluster2$title[cluster2$title %in% c1])

(c1_not_in_c2)
(c2_not_in_c1)
(common)
c1
```

Binning
```{r}
breaks = c(0,500,1000,1500,2000, 4000)
sun_new$category_ordered_rank = findInterval(sun_orig$amazon_category_ordered_units_rank, breaks)
hist(sun_new$category_ordered_rank)

breaks = seq(1,350,70)
sun_new$subcategory_ordered_rank = findInterval(sun_new$amazon_subcategory_ordered_units_rank, breaks)
hist(sun_new$subcategory_ordered_rank)

breaks=seq(1,  35500000, 7100000)
sun_new$page_view_rank_bin = findInterval(sun_new$page_views_rank, breaks)
hist(sun_new$page_view_rank_bin)

breaks=seq(1,  20, 5)
sun_new$unique_visitor_index_bin = findInterval(sun_new$unique_visitors_index, breaks)
hist(sun_new$unique_visitor_index_bin)

breaks=seq(1,  2200000, 420000)
sun_new$order_units_bin = findInterval(sun_new$amazon_ordered_units_rank, breaks)
hist(sun_new$order_units_bin)
```


```{r}
factcols = c( "amazon_category_ordered_sales_rank", "amazon_subcategory_ordered_sales_rank", "amazon_ordered_sales_rank",   "page_views_rank", "customer_reviews", "average_customer_review", "page_views_index", "unique_visitors_index", "amazon_ordered_units_rank", "amazon_category_ordered_units_rank", "amazon_category_shipped_units_rank")

fca_var=sun[,factcols] #= lapply(sun[factcols], factor)
#sapply(sun, function(x) sum(is.na(x)))
ggcorr(as.matrix(fca_var))
cortest.bartlett(as.matrix(fca_var))

#KMO test
#For reference, Kaiser put the following values on the results: - 0.00 to 0.49 unacceptable. - 0.50 to 0.59 miserable. - 0.60 to 0.69 mediocre. - 0.70 to 0.79 middling. - 0.80 to 0.89 meritorious. - 0.90 to 1.00 marvelous.
KMO(as.matrix(fca_var))

#ticker lewis close to 0.09 and RMSE very small. The root mean square of residuals (RMSR) is 0.04. This is acceptable as this value should be closer to 0. RMSEA (Root Mean Square Error Approximation) index = 0.07 which is > 0.05
fca_num = fa.parallel(fca_var, fm = 'pa', fa = 'fa')
fca_rotate <- fa(fca_var,nfactors = 4,rotate = "none",fm="pa")
fca_rotate
print(fca_rotate$loadings,cutoff = 0.5)
fa.diagram(fca_rotate,cut = 0.5)
```

```{r}
num_var = sun[,c(13:15, 25, 29,  39, 41, 43)]
ggcorr(as.matrix(num_var))
cortest.bartlett(as.matrix(num_var))

#scale all the numerical features
num_var_scale=scale(num_var)

sunPCA = prcomp(num_var, scale = FALSE)
plot(sunPCA, type="l") #variance at second component
summary(sunPCA)
sunPCA$rotation
d3heatmap::d3heatmap(sunPCA$rotation, dendrogram = "none")
vars_transformed = apply(sunPCA$x, 2, var)
vars_transformed
vars_transformed/sum(vars_transformed)  #PC1 explains 36% variation and PC2 explains 20% and PC3 explains 13% adding 70%

# First three principal components explains a lot
comp = data.frame(sunPCA$x[,1:3])
# Plot
plot(comp, pch=16, col=rgb(0,0,0.5))

sunpredictPCA = predict(sunPCA, sun[,colnames(num_var)])
sunPCAcols <- cbind(sun, as.data.frame(sunpredictPCA)[,1:3])
```

```{r}
PCAFA <- cbind(sun, as.data.frame(sunpredictPCA)[,1:3], as.data.frame(fca_rotate$scores))

```


```{r}
set.seed(145)
library(factoextra)

fviz_nbclust(PCAFA[,c('PC1', 'PC2', 'PA1', 'PA2','PA3', 'PA4')], kmeans, method = "wss")  #2clusters 0r 5
fviz_nbclust(PCAFA[,c('PC1', 'PC2', 'PA1', 'PA2','PA3', 'PA4')], kmeans, method = "silhouette") #the second method points to 5

```
```{r}
new_data=cbind(num_var_scale, scale(sun[,factcols]), sun[, names(sun) %in% c("title", "upc_code", "asin","category", "subcategory", "platform_type", "week_number")])
#new_data = PCAFA[, c(5,6, 8, 10:14,17:19, 33:37, 39, 41, 43:44, 47:49)]
kClusters = 2
kmeansPCA = kmeans(PCAFA[,c('PC1', 'PC2', 'PA1', 'PA2','PA3', 'PA4')], kClusters, nstart=25, iter.max = 1000)
clusplot(new_data, kmeansPCA$cluster, color=T, shade=F,labels=0,lines=0, main='k-Means Cluster Analysis')

ggplot(PCAFA, aes(x=PC1, y=PC2)) + 
    geom_point(aes(fill=factor(kmeansPCA$cluster)),
               colour='black',
               pch=21,
               size=2) +
    scale_fill_manual(values = c("black","red", 'green', 'blue', "purple", "orange","white")) +
    guides(fill=guide_legend(title="Cluster")) +
    theme_bw()
kmeansPCA$tot.withinss

```


```{r}
#library(dplyr)
library(reshape2)
sort(table(kmeansPCA$clust))
sunclust = names(sort(table(kmeansPCA$clust)))
#sunCluster = sun_new %>% select(asin:title, product_group:subcategory, list_price:orders, unfilled_customer_ordered_units: sellable_on_hand_units)
#sunCluster = sun_new[,!names(sun_new) %in% c("ordered_units", "log_order_units", "week_start", "week_end", "release_date")] #%>% select(asin:title, list_price:orders, unfilled_customer_ordered_units:week_number)

sunCluster=new_data
cluster1=sunCluster[kmeansPCA$clust==sunclust[1],]
c1_uniq=as.data.frame(as.character(unique(cluster1$title)))
names(c1_uniq) = "cluster1"
c1_uniq_week=as.character(sort(unique(cluster1$week_number)))

ggplot(data= melt(cluster1), aes(x=variable, y=value)) +
    stat_boxplot(geom ='errorbar') +
    geom_boxplot(aes(fill=variable)) +
    coord_cartesian(ylim = c(0, 12)) +
    theme(axis.text.x = element_text(angle = 90, hjust = 1), legend.position="none") 

cluster2=sunCluster[kmeansPCA$clust==sunclust[2],]
c2_uniq=as.data.frame(as.character(unique(cluster2$title)))
names(c2_uniq) = "cluster2"
c2_uniq_week=as.character(sort(unique(cluster2$week_number)))

ggplot(data= melt(cluster2), aes(x=variable, y=value)) +
    stat_boxplot(geom ='errorbar') +
    geom_boxplot(aes(fill=variable)) +
    coord_cartesian(ylim = c(0, 7.5)) +
    theme(axis.text.x = element_text(angle = 90, hjust = 1), legend.position="none") 

cluster3=sunCluster[kmeansPCA$clust==sunclust[3],]
c3_uniq=as.data.frame(as.character(unique(cluster3$title)))
names(c3_uniq) = "cluster3"
c3_uniq_week=as.character(sort(unique(cluster3$week_number)))

ggplot(data= melt(cluster3), aes(x=variable, y=value)) +
    stat_boxplot(geom ='errorbar') +
    geom_boxplot(aes(fill=variable)) +
    coord_cartesian(ylim = c(0, 4)) +
    theme(axis.text.x = element_text(angle = 90, hjust = 1), legend.position="none") 

cluster4=sunCluster[kmeansPCA$clust==sunclust[4],]
c4_uniq=as.data.frame(as.character(unique(cluster4$title)))
names(c4_uniq) = "cluster4"
c4_uniq_week=as.character(sort(unique(cluster4$week_number)))

ggplot(data= melt(cluster4), aes(x=variable, y=value)) +
    stat_boxplot(geom ='errorbar') +
    geom_boxplot(aes(fill=variable)) +
    coord_cartesian(ylim = c(0, 12)) +
    theme(axis.text.x = element_text(angle = 90, hjust = 1), legend.position="none") 

cluster5=sunCluster[kmeansPCA$clust==sunclust[5],]
c5_uniq=as.data.frame(as.character(unique(cluster5$title)))
names(c5_uniq) = "cluster5"
c5_uniq_week=as.character(sort(unique(cluster5$week_number)))

ggplot(data= melt(cluster5), aes(x=variable, y=value)) +
    stat_boxplot(geom ='errorbar') +
    geom_boxplot(aes(fill=variable)) +
    coord_cartesian(ylim = c(0, 7.5)) +
    theme(axis.text.x = element_text(angle = 90, hjust = 1), legend.position="none") 

cluster6=sunCluster[kmeansPCA$clust==sunclust[6],]
c6_uniq=as.data.frame(as.character(unique(cluster6$title)))
names(c6_uniq) = "cluster6"
c6_uniq_week=as.character(sort(unique(cluster6$week_number)))

ggplot(data= melt(cluster5), aes(x=variable, y=value)) +
    stat_boxplot(geom ='errorbar') +
    geom_boxplot(aes(fill=variable)) +
    coord_cartesian(ylim = c(0, 7.5)) +
    theme(axis.text.x = element_text(angle = 90, hjust = 1), legend.position="none") 


library(qpcR)
product_clusters=qpcR:::cbind.na(c1_uniq, c2_uniq) #, c3_uniq, c4_uniq, c5_uniq, c6_uniq)
product_clusters

library(cluster)
library(plotly)
ggplot(cluster2, aes(x=as.factor(platform_type), fill=subcategory)) + 
  geom_bar()
```

